/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
//#include "adc.h"
#include "button.h"
#include "interrupt.h"
#include "led.h"
#include "timer.h"
//#include "ASCLIN_Shell_UART.h"
#include "light_sensor.h"
#include "pwm.h"
#define BUTTON_RELEASED 1
#define BUTTON_PUSHED 0

#define PC0_BIT_LSB_IDX 3
#define PC1_BIT_LSB_IDX 11
#define PC2_BIT_LSB_IDX 19
#define PC3_BIT_LSB_IDX 27
#define PC5_BIT_LSB_IDX 11
#define PC7_BIT_LSB_IDX 27
#define P0_BIT_LSB_IDX 0
#define P1_BIT_LSB_IDX 1
#define P2_BIT_LSB_IDX 2
#define P3_BIT_LSB_IDX 3

#define P5_BIT_LSB_IDX 5
#define P7_BIT_LSB_IDX 7

unsigned int button_status = BUTTON_RELEASED; // 1 :  released , 0: pushed

IfxCpu_syncEvent g_cpuSyncEvent = 0;
//__interrupt(0x0A) __vector_table(0)
// void ERU0_ISR(void)
//{
//    RGB_rotate();
//}
__interrupt(0x0B) __vector_table(0)
 void CCU60_T12_ISR(void)
{
     unsigned int adc_result = 0;
     VADC_light_sensor_startConversion();
//     VADC_startConversion();
     adc_result = VADC_light_sensor_readResult();
     if (adc_result >= 3096) {
//         P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;    // LED RED D9 (RGB)
//         P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX); // LED GREEN D10 (RGB)
//         P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX); // LED BLUE D11 (RGB)
         change_duty_ratio(1250);
     } else if (adc_result >= 2048) {
//         P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX); // LED RED D9 (RGB)
//         P10_OUT.U |= (0x1 << P5_BIT_LSB_IDX);  // LED GREEN D10 (RGB)
//         P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX); // LED BLUE D11 (RGB)
         change_duty_ratio(6150);
     } else if (adc_result >= 1024) {
//         P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX); // LED RED D9 (RGB)
//         P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX); // LED GREEN D10 (RGB)
//         P10_OUT.U |= (0x1 << P3_BIT_LSB_IDX);  // LED BLUE D11 (RGB)
         change_duty_ratio(12500);
     } else {
//         P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;   // LED RED D9 (RGB)
//         P10_OUT.U |= (0x1 << P5_BIT_LSB_IDX); // LED GREEN D10 (RGB)
//         P10_OUT.U |= (0x1 << P3_BIT_LSB_IDX); // LED BLUE D11 (RGB)
     }
//     RGB_rotate();

}
__interrupt(0x0C) __vector_table(0)
 void ERU1_ISR(void)
{
    if( (P02_IN.U & (0x1<<P0_BIT_LSB_IDX)) == 0)
    {
        button_status = BUTTON_PUSHED;
    }
    else
    {
        button_status = BUTTON_RELEASED;
    }
    change_freq(button_status);

}

int core0_main(void) {
    //    unsigned char prev_prev_value = 1;
    //    unsigned char prev_value = 1;
    //    unsigned char cur_value = 1;

    //    unsigned char edge_detector_prev;
    //    unsigned char edge_detector_cur;

    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
        initLED();
    //    initButton();
//    initVADC();
    initCCU60();
    //    initERU();
    //    initERU02();
//    initShellInterface();
//    initREDLED_PWM();
    initGTM();
    initREDLED_PWM();

    P10_OUT.U = 0x1 << P1_BIT_LSB_IDX;
//    P10_OUT.U = 0x1 << P2_BIT_LSB_IDX;
    VADC_light_sensor_init();
    PWM_trigger();
    while (1) {
//        runShellInterface();
    }
    return (1);
}
